### ISSUE TITLE
Add support for Conversations

### ISSUE THREAD

**Issue by singpolyma** [mohak1712/Insta-Chat#2]

**Comment by mohak1712** [comment]
can u share the play store link

**Comment by singpolyma** [comment]
https://play.google.com/store/apps/details?id=eu.siacs.conversations

**Comment by mohak1712** [comment]
Does this app support wear devices?

**Comment by singpolyma** [comment]
I don't know. Is it hard to add wear support if it's not there yet?

**Comment by mohak1712** [comment]
I can't add this feature to apps that don't support wear because u cannot reply to messages without wear support.

**Comment by singpolyma** [comment]
I'm sure if it doesn't support wear yet that there'd be no objection to adding it. It might even be there, I just have no wear devices to test :)

**Comment by mohak1712** [comment]
As of now the app doesn't have wear support

**Comment by subpub** [comment]
There's a PR for it currently https://github.com/siacs/Conversations/pull/2441 @singpolyma you can reopen this soon :)

**Comment by mohak1712** [comment]
sure

**Comment by morgenroth** [comment]
Android Wear is already supported by Conversations. The PR siacs/Conversations#2441 add support for Android Auto.

**Comment by subpub** [comment]
why closed?

**Comment by tajgarhwa** [comment]
App is not available in play store way???
